### ISSUE TITLE
PyTorch and TensorFlow version

### ISSUE THREAD

**Issue by GabrielLin** [abhigupta768/publication-venue-recommender#1]
Thanks for your great work. Could you please tell me which version of PyTorch and TensorFlow do you use? Thanks.

**Comment by abhigupta768** [comment]
Hi, the PyTorch version used for this project is 1.7.1 with CUDA 10.1. PyTorch does not need TensorFlow as a backend. So you would not need a version for that.

Please let me know if you have any questions. Thanks!

**Comment by GabrielLin** [comment]
@abhigupta768 Thank you for your rapid reply. Got it.
